name: build-xetex-native
run-name: ${{ github.actor }} is building a native xetex executable
on: [push]
jobs:
  build-xetex-native:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install base dependencies
        run: sudo apt install autoconf build-essential libtool pkg-config
      - name: Install fontconfig
        run: sudo apt install libfontconfig1-dev
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: x64
      - name: Build native xetex executable
        run: cd xetex && CC=gcc CXX=g++ ./build.sh --parallel
